services:
  nginx:
    ports:
      - "443:443"
    env_file:
      - ./.env
  mariadb:
    ports:
      - "3306:3306"
    env_file:
      - ./.env
  wordpress:
    ports:
      - "9000:9000"
    env_file:
      - .env

networks:
  inception:
    driver: bridge
