services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/xriera-c/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/xriera-c/data/wordpress
      o: bind
